spring:
  datasource:
    url: jdbc:h2:mem:~/spring-demo-coffee
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always # 상세 정보
  endpoints:
    web:
      exposure:
        include:
          - env
          - info
          - health

greeting:
  name: Soonho
  coffee: ${greeting.name} is drinking Cafe Cereza

droid:
  id: droid-id
  description: droid-description
