apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
spec:
  # 1 파드 3개 배포
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
    spec:
      affinity:
        # 2 Pod AntiAffinity 설정
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector: # 2-1 레이블 조건 설정
                matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                      - echo
              topologyKey: "kubernetes.io/hostname" # 2-2 조건 적용 대상
      containers:
        - name: nginx
          image: ghcr.io/jpubdocker/simple-nginx-proxy:v0.1.0
          env:
            - name: NGINX_PORT
              value: "80"
            - name: SERVER_NAME
              value: "localhost"
            - name: BACKEND_HOST
              value: "localhost:8080"
            - name: BACKEND_MAX_FAILS
              value: "3"
            - name: BACKEND_FAIL_TIMEOUT
              value: "10s"
          ports:
            - name: http
              containerPort: 80
        - name: echo
          image: ghcr.io/jpubdocker/echo:v0.1.0
