apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: echo
  labels:
    app.kubernetes.io/name: echo
spec:
  scaleTargetRef: # 1 HPA 대상 리소스
    apiVersion: apps/v1
    kind: Deployment
    name: echo
  minReplicas: 1 # 3-1 replica 수(min)
  maxReplicas: 3 # 3-2 replica 수(max)
  metrics:
    - type: Resource # 2 HPA 동작을 위한 임곗값 설정
      resource:
        name: cpu # 2-1 대상은 CPU
        target:
          type: Utilization # 2-2 CPU 사용률
          averageUtilization: 40 # 2-3 임곗값
