apiVersion: apps/v1
kind: Deployment
metadata:
  name: print-version
  labels:
    app: print-version
spec:
  replicas: 1
  selector:
    matchLabels:
      app: print-version
  template:
    metadata:
      labels:
        app: print-version
    spec:
      containers:
      - name: print-version
        image: ghcr.io/jpubdocker/print-version:v0.0.1
        livenessProbe: # 1
          exec:
            command:
            - cat
            - /var/tmp/libe.txt # 1-1
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe: # 2
          httpGet:
            path: /hc
            port: 8080
          timeoutSeconds: 3
          initialDelaySeconds: 15
        ports:
        - containerPort: 8080
