apiVersion: v1
kind: Service
metadata:
  name: print-version
  labels:
    app: print-version
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: print-version # 1
    color: blue # 2
