apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echo
  labels:
    app: echo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo
  template: # template 하위의 파드 리소스 정의와 같음
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: nginx
        image: ghcr.io/jpubdocker/simple-nginx-proxy:v0.1.0
        env:
        - name: NGINX_PORT
          value: "80"
        - name: SERVER_NAME
          value: "localhost"
        - name: BACKEND_HOST
          value: "localhost:8080"
        - name: BACKEND_MAX_FAILS
          value: "3"
        - name: BACKEND_FAIL_TIMEOUT
          value: "10s"
        ports:
        - containerPort: 80
      - name: echo
        image: ghcr.io/jpubdocker/echo:v0.1.0
        ports:
        - containerPort: 8080
