server:
  port: 8081

jwt:
  key: Mjw343kd

publicKey: -----BEGIN PUBLIC KEY-----
  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlrWgE40JNHXtzQdhVgES
  24SrZvSrVStc7lEwJddofkI72q802xZBRoYCu2mT8HqBKDGIEWqiLMyUxPSy5FeM
  0ELVMR1C8Ja550MH8Kz6UFH57kSy58WOGNjdyIYJ6SG062ITTJTVz1oLYsyN2xQB
  p4juJEUzrA8FFrRU09Q5F3CkncxAf0ERLm9G3/pOGLj9KMXMReQ1ZyMsXgHD4Zc+
  3uXAvr7+SQ0SWP2cWeqkg+oAjQv/tGVjOqevNHWu6gGXRvRJ3oYzYNXmx2sDzIge
  89qW4fRZHHHO2DGutDpl5MmQjbL78u15nzIlJg439foz/n6+aRv7596eXRdAkZfT
  1QIDAQAB
  -----END PUBLIC KEY-----
  -----BEGIN CERTIFICATE-----
  MIIDcTCCAlmgAwIBAgIETCuS8DANBgkqhkiG9w0BAQsFADBpMRAwDgYDVQQGEwdV
  bmtub3duMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYD
  VQQKEwdVbmtub3duMRAwDgYDVQQLEwdVbmtub3duMQ0wCwYDVQQDEwRzc2lhMB4X
  DTIyMTAwNDIwMDc0NFoXDTIzMDEwMjIwMDc0NFowaTEQMA4GA1UEBhMHVW5rbm93
  bjEQMA4GA1UECBMHVW5rbm93bjEQMA4GA1UEBxMHVW5rbm93bjEQMA4GA1UEChMH
  VW5rbm93bjEQMA4GA1UECxMHVW5rbm93bjENMAsGA1UEAxMEc3NpYTCCASIwDQYJ
  KoZIhvcNAQEBBQADggEPADCCAQoCggEBAJa1oBONCTR17c0HYVYBEtuEq2b0q1Ur
  XO5RMCXXaH5CO9qvNNsWQUaGArtpk/B6gSgxiBFqoizMlMT0suRXjNBC1TEdQvCW
  uedDB/Cs+lBR+e5EsufFjhjY3ciGCekhtOtiE0yU1c9aC2LMjdsUAaeI7iRFM6wP
  BRa0VNPUORdwpJ3MQH9BES5vRt/6Thi4/SjFzEXkNWcjLF4Bw+GXPt7lwL6+/kkN
  Elj9nFnqpIPqAI0L/7RlYzqnrzR1ruoBl0b0Sd6GM2DV5sdrA8yIHvPaluH0WRxx
  ztgxrrQ6ZeTJkI2y+/LteZ8yJSYON/X6M/5+vmkb++fenl0XQJGX09UCAwEAAaMh
  MB8wHQYDVR0OBBYEFHl24aQiWiujjPcqQZeBOnf4nLSIMA0GCSqGSIb3DQEBCwUA
  A4IBAQAIn7f/QCOgss5IDaj8cijZepRVc8dkMlhkkKB0bDouImz3HquZf8YwE1G/
  AzO8yaW3gUpEmRqUZ0mWGW7bNhnQNvtfUa0f4OMdX/45arZqe2T+4GjxqAGLWmdE
  9UkOgKT8kb+82ITbWjmyasCBxpyx59jarlq90rANlIzO+uhZBONca9uX169hlNcM
  OrL4OlnBsuvXgxZYxsRBnHcCSY4AXRzec4G02K2Odf95kzeQHg0OF9z1jBlBo6Wg
  r62F0kIpXbYR3XeH7h3V860LBdYnCI+s9m3Dv8zBphYY2XRgvliRQVN3xtfsO3pP
  YTdlD8/4Rmzuwdr12f5r/E6sPrj6
  -----END CERTIFICATE-----